"""Frozen setup contracts for RELATION_DIRECTION_IDENTITY_V1."""

STUDY_ID = "RELATION_DIRECTION_IDENTITY_V1"
SETUP_TERMINAL_STATUSES = frozenset({
    "READY_FOR_A100", "PRIMARY_DATASET_BLOCKED",
    "INSUFFICIENT_EXTERNAL_DATASET_DIVERSITY", "FROZEN_INPUT_MISMATCH",
    "STORAGE_CONTRACT_FAILED", "SETUP_VALIDATION_FAILED",
})
