"""Development-only Claim 2 rephrasing-susceptibility pilot."""

SCHEMA_VERSION = 1
STATUS_READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
STATUS_READY_FOR_INFERENCE = "READY_FOR_INFERENCE"
STATUS_ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
STATUS_PIPELINE_FAILURE = "PIPELINE_FAILURE"
